#!/usr/bin/env php
<?php

require_once __DIR__.'/CalendarKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new CalendarKernel('dev', true);

$application = new Application($kernel);
$application->run();
