#kernel.config:
#    charset:       UTF-8
#    error_handler: null

app.config:
    csrf_secret: xxxxxxxxxx
    charset:     UTF-8
    error_handler: null
    router:      { resource: "%kernel.root_dir%/config/routing.yml" }
   # validation:  { enabled: true, annotations: true }
    templating:
        escaping:       htmlspecialchars
      #assets_version: SomeVersionScheme

## Twig Configuration
#twig.config:
#    auto_reload: true

# Doctrine Configuration
doctrine.dbal:
    dbname:   calendar
    user:     root
    password: ~

doctrine.orm: ~

## Swiftmailer Configuration
#swift.mailer:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
